name: Deploy snapshot

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v2

      - name: Set up Java for publishing snapshot to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Configuring Maven cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Get the branch name
        id: branch
        uses: mdecoleman/pr-branch-name@1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build branch snapshot version name
        id: snapshot_name
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q)
          SNAPSHOT_VERSION=$(cut -d - -f1 <<< $VERSION)
          SNAPSHOT_VERSION+=-
          SNAPSHOT_VERSION+=$BRANCH_NAME
          echo ::set-output name=SNAPSHOT_VERSION::$SNAPSHOT_VERSION
        env:
          BRANCH_NAME: ${{ steps.branch.outputs.branch }}

      - name: Update version name to be deployed
        run: mvn versions:set -DnewVersion=$SNAPSHOT_VERSION
        env:
          SNAPSHOT_VERSION: ${{ steps.snapshot_name.outputs.SNAPSHOT_VERSION }}

      - name: Deploy to the Maven Central Repository
        run: mvn -B -ntp -Possrh clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

      - name: Configure Git
        run: |
          git config user.email "noreply@github.com"
          git config user.name "Github"

      - name: Create Snapshot tag
        run: |
          git tag -f -a v$SNAPSHOT_VERSION -m "Snapshot version ${SNAPSHOT_VERSION}"
          git push -f --tags
        env:
          SNAPSHOT_VERSION: ${{ steps.snapshot_name.outputs.SNAPSHOT_VERSION }}
